### ISSUE TITLE
About the accuracy of your method to measure LAI

### ISSUE THREAD

**Issue by QiYunZeng** [ETC-UA/LeafAreaIndex.jl#2]
```
    Excuse me,can I ask some questions about your method to measure LAI?
    Do you use the instrument to measure the LAI of the selected experimental area? For example,LAI2000 or TRAC and so on. 
   Can you tell me  the  numerical  difference between your method to measure LAI and the instrument to measure LAI?
    I am really looking forward to your reply!
```

**Comment by Ken-B** [comment]
Hi,

Just to make sure, this package measures the LAI from hemispherical pictures, basically pictures taken with a wide angle/fisheye lens on a digital camera pointed at the zenith. A good introduction on this topic is [Weiss et al, 2004, agricultural and forest meteorology](http://www.researchgate.net/profile/Inge_Jonckheere/publication/222931516_Review_of_methods_for_in_situ_leaf_area_index_%28LAI%29_determination_Part_II._Estimation_of_LAI_errors_and_sampling/links/09e4150cefe5a4fea5000000.pdf). See also the [documentation of this package](https://leafareaindexjl.readthedocs.org/en/latest/).

For a comparison with LAI2000, I refer to [Thimonier et al 2010](http://www.schleppi.ch/patrick/publi/pdf/atal10b.pdf).

Currently a comparison with a Lidar and sun scan is being undertaken here in Antwerp, but the results are not yet available.

Kind regards,
Ken
edit: Lidar instead of Licor..

**Comment by QiYunZeng** [comment]
Hi,ken
         Thank you for your patience reply!
         Recently I have selected a experimental area to conduct a experiment to measure LAI, but the result by my method  is very different from the result that use the instrument( LAI2000) to measure ,the deviation range is 0.2~0.6 . My method also adopts taking hemispherical pictures. Could you tell me what's the best time to take hemispherical pictures of one day or what I should pay attention to when taking hemispherical pictures? 
         And can you tell me the deviation range between your method of calculating the LAI and the instrument that you use to measure the LAI ?
        Is  your method also available for calculating the LAI of corn or just available for forest? 
        Look forward to your reply!

**Comment by Ken-B** [comment]
A good time is either in the early morning at dawn or in the evening at dusk, to prevent any direct sunlight in the lens. However, it's sometimes difficult to take all the pictures in this short time frame. Better yet is during the day with overcast cloudy conditions. The ETC team at Antwerp University is finishing a full protocol that will be placed online.
For a comparison of direct and indirect methods for LAI measurements, I refer to the references in my previous message.
The current code processes upward hemisperical pictures, for downward pictures I refer to the (freely available) CAN-EYE software.

**Comment by QiYunZeng** [comment]
Thank you for your patience reply! I will take your advise.
